version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.4.1-fpm
      - image: circleci/mysql:5.7
        command: mysqld --default-authentication-plugin=mysql_native_password
        envirionment: # MySQLの初期設定
          - APP_DEBUG: true
          - APP_ENV: circle
          - DB_CONNECTION: circle_test
          - MYSQL_ALLOW_EMPTY_PASSWORD: true

    working_directory: ~/repo

    steps:
      - checkout

      - run:
        name: test_setup # テストを行うために必要なライブラリなどのインストール
        command: |
          sudo apt-get update && sudo apt-get install -y libpng-dev libjpeg-dev |
          sudo docker-php-ext-configure gd --with-png-dir=/usr/include --with-jpeg-dir=/usr/include |
          sudo docker-php-ext-install pdo_mysql gd

      - restore_cache: # composer.jsonのキャッシュがあれば利用
          keys:
            - v1-dependencies-{{ checksum "composer.json" }}
            - v1-dependencies-

      - run:
          name: composer install
          command: composer install -n --prefer-dist

      - save_cache: # composer.jsonをキャッシュ
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}

      - run:
          name: migration
          command: php artisan migrate --env=circle

      - run: # envファイルをcircleci用のものに変更
          name: env_copy
          command: rm .env.testing && ln -s .env.circle .env.testing
